docker-build-master:
  variables:
    buildx: "yes"
  image: ahmetozer/dind:latest
  stage: build
  before_script:
    - /src/start-docker.sh
    - docker login -u "ahmetozer" -p "$dhub"
  script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm --push -t ahmetozer/net-tools-service -t ahmetozer/net-tools-service:$CI_COMMIT_TAG	.
  only:
    - master
